services:
  api:
    build:
      context: ./docker/api-cli
    container_name: adom_api
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app
      REVERB_HOST: reverb
      REVERB_PORT: 8080
      REVERB_SCHEME: http
    depends_on:
      - postgres
      - reverb
  php-fpm:
    build:
      context: ./docker/api
    container_name: adom_php_fpm
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app
      REVERB_HOST: reverb
      REVERB_PORT: 8080
      REVERB_SCHEME: http
    depends_on:
      - postgres
      - reverb
    command: bash -lc "composer install --no-interaction --prefer-dist && php artisan key:generate --force && php artisan migrate --force || true && php-fpm"

  app-public:
    build:
      context: ./docker/app-public
    container_name: adom_app_public
    ports:
      - "5173:5173"
    working_dir: /usr/src/app
    volumes:
      - ./app-public:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    command: sh -lc "[ -f .env ] || cp .env.example .env; npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - php-fpm

  app-admin:
    build:
      context: ./docker/app-admin
    container_name: adom_app_admin
    ports:
      - "5174:5173"
    working_dir: /usr/src/app
    volumes:
      - ./app-admin:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    command: sh -lc "[ -f .env ] || cp .env.example .env; npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      - php-fpm

  postgres:
    build:
      context: ./docker/postgres
    container_name: adom_postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF-8 --encoding=UTF8"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # init scripts not needed when using POSTGRES_DB with desired locale
    ports:
      - "5433:5432"

  reverb:
    build:
      context: ./docker/api-cli
    container_name: adom_reverb
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app
      REVERB_APP_ID: ${REVERB_APP_ID:-1}
      REVERB_APP_KEY: ${REVERB_APP_KEY}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET}
      REVERB_HOST: ${REVERB_HOST:-localhost}
      REVERB_PORT: ${REVERB_PORT:-8080}
      REVERB_SCHEME: ${REVERB_SCHEME:-http}
      # Принудительно указываем, что мы не на Windows
      PHP_OS: Linux
    depends_on:
      - postgres
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.27-alpine
    container_name: adom_nginx
    depends_on:
      - php-fpm
      - app-public
      - app-admin
      - reverb
    ports:
      - "80:80"
      - "5175:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    restart: unless-stopped

volumes:
  pgdata:


